name: BidderBidder CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create google-service
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json
      - name: Create data dir
        run: mkdir ./app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/data
      - name: Create Constants
        run: echo '${{ secrets.CONSTANTS }}' > ./app/src/main/kotlin/com/fakedevelopers/bidderbidder/api/data/Constants.kt
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.SIGN_KEY }}
          keystore_password: ${{ secrets.KEY_STORE_PASSWORD }}
          key_alias: ${{ secrets.ALIAS }}
          key_password: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
         BUILD_TOOLS_VERSION: "30.0.2"
      - name: signed app bundle
        uses: actions/upload-artifact@v3
        with:
          path: ./app/build/outputs/apk/release/app-release.apk
